### ISSUE TITLE
doesn't compile on latest Ubuntu

### ISSUE THREAD

**Issue by rebroad** [madscientist42/scratchbox2#1]
I get this error:-

[CC] preload/system.o
../preload/system.c:46:28: fatal error: bits/libc-lock.h: No such file or directory

**Comment by madscientist42** [comment]
Yeah, they've changed things out from underneath.  I was in the middle of a
re-work.  Give me a couple of days and the correction for at least this
will be up.

**Comment by wambu-i** [comment]
Was this issue ever fixed? 
I'm still getting it when I try to build sb2.

**Comment by madscientist42** [comment]
Not yet.  I'd been busy with a few other things and projects and was
unaware that anyone had logged a bug against my repo.  I'll get to it here
shortly.

**Comment by madscientist42** [comment]
Give me a bit.  I first thought that I'd had one slip past me...it seems that I might've fixed it and not pushed/closed out the issue.

I should be able to sort this out quickly.

**Comment by madscientist42** [comment]
Sorry about that.  Was facing a lot of issues when the issue came out (including being out of work...)- this shouldn't have slipped through the cracks like it did there.  I have pushed a patch to the tip of master that should work for now on things.  

Basically, the upstream for glibc opted to not even package the referred to headers in toto as of about three or four releases ago, which broke us.  I *was* at one point in the middle of a cleanup  that made this issue less likely to break us.  I'm going to get back to this shortly- but this should "fix" it for now.

**Comment by wambu-i** [comment]
@madscientist42  Hey, no problem! Thanks for getting back to me.  
I actually got it to kind of work by commenting out that line. I will try it again.

I'm also having another problem when I try to configure Scratchbox. 

`Using /usr/bin/arm-linux-gnueabi-gcc to detect target architecture:
Finished writing sb2.gcc.config
gcc configured.
sb2-init: Target architecture is 'arm'
sb2-init: Host architecture is 'x86_64'
Finished writing sb2.config
sb2-init: Creating Debian build system settings for this target:
sb2-init: configuring libtool for this target:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... 
configure: error: C compiler cannot create executables
See `config.log' for more details.
`

While my `config.log` shows this:
`Thread model: posix
gcc version 5.3.0 (OpenWrt GCC 5.3.0 49805) 
configure:2849: $? = 0
configure:2856: gcc -V >&5
x86_64-openwrt-linux-gcc: error: unrecognized command line option '-V'
x86_64-openwrt-linux-gcc: fatal error: no input files
compilation terminated.
configure:2859: $? = 1
configure:2882: checking for C compiler default output file name
configure:2909: gcc -I/home/openwrt/staging_dir/target-
x86_64_musl-1.1.14/usr/include  -L/home/openwrt/staging_dir/target-x86_64_musl-1.1.14/usr/lib conftest.c  >&5
configure:2912: $? = 0
configure:2950: result: a.out
configure:2967: checking whether the C compiler works
configure:2977: ./a.out
./configure: line 2978: ./a.out: No such file or directory
configure:2980: $? = 127
configure:2989: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details.
`

Or sometimes I'll get `configure:2564: checking for gcc
configure:2580: found /usr/bin/gcc
configure:2591: result: gcc
configure:2829: checking for C compiler version
configure:2836: gcc --version >&5
./configure: line 2837: /usr/bin/gcc: No such file or directory
configure:2839: $? = 127
configure:2846: gcc -v >&5
./configure: line 2847: /usr/bin/gcc: No such file or directory
configure:2849: $? = 127
configure:2856: gcc -V >&5
./configure: line 2857: /usr/bin/gcc: No such file or directory
configure:2859: $? = 127
configure:2882: checking for C compiler default output file name
configure:2909: gcc conftest.c >&5
./configure: line 2910: /usr/bin/gcc: No such file or directory
configure:2912: $? = 127
configure:2950: result:
configure: failed program was:
| /* confdefs.h. */
| #define PACKAGE_NAME "libtool"
| #define PACKAGE_TARNAME "libtool"
| #define PACKAGE_VERSION "1.5.26"
| #define PACKAGE_STRING "libtool 1.5.26"
| #define PACKAGE_BUGREPORT "bug-***@gnu.org"
| #define PACKAGE "libtool"
| #define VERSION "1.5.26"
| /* end confdefs.h. */
|
| int
| main ()
| {
|
| ;
| return 0;
| }
configure:2957: error: C compiler cannot create executables
See `config.log' for more details.`

Am I doing something wrong? I've checked that my build GCC does indeed work, but I can't figure out anything else.

**Comment by wambu-i** [comment]
@madscientist42 I tried building again after your fixes, but I get these surprising many errors now.

[sb2_build.txt](https://github.com/madscientist42/scratchbox2/files/1254724/sb2_build.txt)
